// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTransaction(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddTransaction'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetCryptosList() {
  return window['go']['main']['App']['GetCryptosList']();
}

export function GetTransactions() {
  return window['go']['main']['App']['GetTransactions']();
}
